name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ../passwordGeneratorGo/Dockerfile
          push: true
          tags: your-dockerhub-username/password-generator:latest

      - name: Deploy (if using Kubernetes or another platform)
        run: |
          # Commands to deploy, e.g., kubectl apply -f your_deployment_file.yaml
          # or other platform-specific CLI commands

